version: '3.8'

services:
  churn_predictor:
    build: .
    container_name: ecommerce_churn_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
